name: flutter_form_mailer
description: "A Flutter package for easy form submissions via email using SMTP."
version: 1.0.0
homepage: "https://github.com/muhammadhusnain531/flutter_form_mailer"
repository: "https://github.com/muhammadhusnain531/flutter_form_mailer"
issue_tracker: "https://github.com/muhammadhusnain531/flutter_form_mailer/issues"
documentation: "https://github.com/muhammadhusnain531/flutter_form_mailer/wiki"
topics:
  - flutter
  - email
  - form
  - smtp

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mailer: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
